codeforamerica/honeycrisp-gem

- .circleci/config.yml
- Gemfile.lock
- README.md
- cfa-styleguide.gemspec
- spec/spec_helper.rb
- spec/support/pre_documentation_formatter.rb
Runs specs with nice formatting
https://github.com/codeforamerica/cfa-styleguide-gem/issues/4
> Add CircleCI config

- Gemfile.lock
- app/helpers/cfa/styleguide/cfa_form_builder.rb
- app/models/cfa/styleguide/form_example.rb
- lib/cfa/styleguide/version.rb
- spec/feature/pages_spec.rb
- spec/helpers/cfa_form_builder_spec.rb
- spec/support/match_html.rb
- spec/test_app/app/views/pages/root.html.erb
> Add CfaFormBuilder

- Gemfile.lock
- app/helpers/cfa/styleguide/cfa_form_builder.rb
- lib/cfa/styleguide/version.rb
- spec/helpers/cfa_form_builder_spec.rb
For use in yes/no button patterns, or any buttons that act like links.
> Add cfa_single_tap_button to FormBuilder

- Gemfile.lock
- app/assets/javascripts/cfa_styleguide_main.js
- app/helpers/cfa/styleguide/cfa_form_builder.rb
- app/models/cfa/styleguide/form_example.rb
- lib/cfa/styleguide/version.rb
- spec/helpers/cfa_form_builder_spec.rb
- spec/test_app/app/views/pages/root.html.erb
Remove hr between 'None' checkbox and the rest of the set
> Add js for checkbox set with none

- cfa-styleguide.gemspec
- spec/spec_helper.rb
- spec/support/system_tests.rb
- spec/system/examples_spec.rb
- spec/system/hello_world_spec.rb
- spec/system/pages_spec.rb
More on how to use at https://guides.rubyonrails.org/testing.html#system-testing & intro at https://medium.com/table-xi/a-quick-guide-to-rails-system-tests-in-rspec-b6e9e8a8b5f6.
Thanks to @bensheldon for inspiration from GCF!
> Transition to using system tests

- README.md
resolves https://github.com/codeforamerica/cfa-styleguide-gem/issues/55
> Add note about changes required to enable variable usage

- CHANGELOG.md
- Gemfile.lock
- README.md
- Rakefile
- cfa-styleguide.gemspec
A first attempt at auto-generating changelog and making a more formal release process.
Begins to address https://github.com/codeforamerica/cfa-styleguide-gem/issues/52
> Add changelog generation and instructions

- app/assets/javascripts/cfa_styleguide_main.js
- app/assets/stylesheets/cfa_styleguide_main.scss
- app/assets/stylesheets/molecules/_show-more.scss
- app/views/cfa/styleguide/pages/index.html.erb
- app/views/components/molecules/_show_more.html.erb
- app/views/examples/molecules/_show_more.html.erb
This PR adds the show more pattern from [GetCalFresh](https://github.com/codeforamerica/gcf-backend/commit/410a93ee58b69c88919a2a59d73a9320fc952004).
Resolves #30
> Add show more pattern to molecules

- app/assets/stylesheets/atoms/_labels.scss
- app/assets/stylesheets/atoms/_variables.scss
- app/views/examples/molecules/_block_input_group.html.erb
- app/views/examples/molecules/_flash_messages.html.erb
- app/views/examples/organisms/_pagination.html.erb
- spec/system/accessibility_spec.rb
- Fixed color contrast
- ensured unique names for radio buttons
- Added label text to buttons and links
> Make accessibility improvements

- app/views/cfa/styleguide/pages/index.html.erb
Rachel suggested this would be useful, so I took a simple pass at adding a link to the Github repo + issues.
> Add link to Github repo and issue submission

- yarn.lock
https://github.com/lodash/lodash/pull/4336
> Upgrade lodash to address CVE

- app/assets/stylesheets/atoms/_form-elements.scss
> Remove margins around `.button` in `.file-upload` so outline is snug 

- app/assets/stylesheets/templates/_styleguide.scss
- app/views/examples/atoms/_colors.html.erb
with color info and better legibility #104
> Update Colors section of styleguide 

- app/assets/stylesheets/atoms/_buttons.scss
- app/assets/stylesheets/molecules/_accordion.scss
- app/views/examples/atoms/_buttons.html.erb
Remove CTA button. Modify button--link class to look exactly like an a tag. Add documentation for buttons. Closes #115
> Button cleanup

- app/assets/stylesheets/molecules/_progress-indicator.scss
- app/views/components/molecules/_progress_indicator.html.erb
fixes issue #151
Co-authored-by: Symonne Singleton <symonne@codeforamerica.org>
> Fix z-index on Progress Indicator Bar

- app/assets/javascripts/sidebar_nav.js
- app/assets/stylesheets/_sidebar-nav.scss
- app/assets/stylesheets/atoms/_base.scss
- app/views/layouts/_sidebar_nav.html.erb
> Fix some issues with sidebar formatting and selection state

- app/assets/javascripts/cfa_styleguide_main.js
- app/assets/stylesheets/organisms/_main-footer.scss
> Create `main-footer__compact` class for compact footer

- app/assets/stylesheets/molecules/_tabs.scss
- app/assets/stylesheets/templates/_styleguide.scss
> Use existing selected tab style

- app/assets/javascripts/sidebar_nav.js
- app/assets/stylesheets/_honeycrisp-compact.scss
- app/assets/stylesheets/atoms/_variables.scss
- app/assets/stylesheets/cfa_styleguide_main.scss
- app/assets/stylesheets/molecules/_data-table.scss
- app/views/cfa/styleguide/pages/form_builder.html.erb
- app/views/cfa/styleguide/pages/honeycrisp_compact.html.erb
- app/views/cfa/styleguide/pages/index.html.erb
- app/views/examples/atoms/_slab_layout.html.erb
- app/views/examples/honeycrisp_compact/_data_table.html.erb
- app/views/layouts/_sidebar_nav.html.erb
- config/routes.rb
- spec/system/pages_spec.rb
- Adds a Honeycrisp Compact page with a compact data table example
- Improves navigation highlighting for top level page and subnavigation section
- Adds subnavigation for form builder
Closes
- https://github.com/codeforamerica/honeycrisp-gem/issues/211
- https://github.com/codeforamerica/honeycrisp-gem/issues/208
- https://github.com/codeforamerica/honeycrisp-gem/issues/206
> Honeycrisp compact

- app/assets/stylesheets/_honeycrisp-compact.scss
- app/views/cfa/styleguide/pages/honeycrisp_compact.html.erb
- app/views/examples/honeycrisp_compact/_buttons.html.erb
- app/views/examples/honeycrisp_compact/_form_elements.html.erb
- Solves #205
- Dropdown story: [#176151526]
- Button story: [#175169414]
> Add compact drop down and button styles

- app/views/examples/atoms/_typography.html.erb
> Use text--help for help text in Honeycrisp guide

- app/assets/images/icon_sort_down.svg
- app/assets/images/icon_sort_neutral.svg
- app/assets/images/icon_sort_up.svg
- app/assets/stylesheets/_honeycrisp-compact.scss
Co-authored-by: Travis Grathwell <tgrathwell@codeforamerica.org>
> Add arrow icons for sortable headers

- Gemfile.lock
- cfa-styleguide.gemspec
- spec/spec_helper.rb
- spec/system/accessibility_spec.rb
> Upgrade axe-matchers to axe-core-rspec

- app/assets/javascripts/cfa_styleguide_main.js
- app/assets/javascripts/version_comment.js
- app/assets/stylesheets/cfa_styleguide_main.scss
- lib/tasks/distribution.rb
- spec/system/distribution_spec.rb
- add comment placeholder to JS and CSS source files
- add `add_version_comment` method to `Distribution` class
- in `Distribution` class, replace placeholder with version and date for assets
- add tests for `add_version_comment`, minified js, and minified css
Closes #276
> added version and date to packaged files

- app/assets/stylesheets/cfa_styleguide_main.scss
- app/assets/stylesheets/honeycrisp/atoms/_links.scss
- app/views/cfa/styleguide/pages/index.html.erb
- app/views/examples/atoms/_links.html.erb
- app/views/examples/molecules/_toolbar.html.erb
Co-authored-by: Alex Gonzalez <agonzalez@codeforamerica.org>
Co-authored-by: Luigi Ray-Montanez <luigi@codeforamerica.org>
> Add skip links from SHIBA and provide example

- README.md
- need another commit to main to update heroku stack
> Update deployment steps in readme

- app/assets/stylesheets/honeycrisp/atoms/_illustrations.scss
> Unsquish cfa_logo_dark in mobile

- app/assets/javascripts/honeycrisp.js
* Extract the follow-up question hiding into its own method
* Call that method after clicking "None of the Above"
> Hide follow-up questions after clicking "None of the Above"

- app.json
> Updating heroku stack config

- lib/sprockets_extension/uglifier_source_maps_compressor.rb
https://github.com/codeforamerica/honeycrisp-gem/pull/334 introduced some rubocop errors
> Fix rubocop errors

- app/assets/javascripts/honeycrisp.js
Addresses #352
https://codeql.github.com/codeql-query-help/javascript/js-xss-through-dom/
> Address Javascript XSS vulnerability

- app/assets/stylesheets/honeycrisp/atoms/_form-elements.scss
- app/helpers/cfa/styleguide/cfa_form_builder.rb
- app/views/examples/form_builder/v1/_cfa_checkbox_set.html.erb
- app/views/examples/form_builder/v1/_cfa_checkbox_set_with_none.html.erb
- app/views/examples/form_builder/v1/_cfa_input_field.html.erb
- app/views/examples/form_builder/v1/_cfa_radio_set_with_follow_up.html.erb
- app/views/examples/form_builder/v1/_cfa_range_field.html.erb
- app/views/examples/form_builder/v1/_cfa_select.html.erb
- spec/helpers/cfa_form_builder_spec.rb
- spec/system/accessibility_spec.rb
For context, see:
https://github.com/codeforamerica/vita-min/pull/5474
https://github.com/newjersey/accessibility-pm/issues/19
> V1 forms a11y updates
