app/assets/javascripts/cfa_styleguide_main.js
lib/cfa/styleguide/version.rb

With accessibility improvements to the form builder (currently in Michigan + Colorado code bases, to be pulled into styleguide), we need a more permissive search for the relevant ancestor to assign 'is-selected' to for radio buttons. Right now, if a validation error is present then a selected radio button doesn't *appear* to be selected.
This change should work for both current cases: what's currently in GCF's form builder (parent), and what is in the newer version (grandparent).

Make radio button 'is-selected' more permissive wrt HTML structure

---

Gemfile.lock
app/controllers/cfa/styleguide/pages_controller.rb
app/views/cfa/styleguide/pages/index.html.erb
app/views/layouts/main.html.erb
lib/cfa/styleguide/version.rb
spec/test_app/app/views/layouts/application.html.erb

Previously, the styleguide pages used whatever application they were
installed-in's application.html. This means if application-specific
routes (like root_path) were included in the layout, the styleguide
would break.
To fix this, we now have a generic application.html layout that all CfA
styleguide pages use by default.
Fixes https://github.com/codeforamerica/cfa-styleguide-gem/issues/9

Declare layout for Styleguide

---

Gemfile.lock
app/views/cfa/styleguide/pages/cbo_analytics.html.erb
app/views/cfa/styleguide/pages/cbo_dashboard.html.erb
app/views/cfa/styleguide/pages/current.html.erb
app/views/cfa/styleguide/pages/custom_docs.html.erb
app/views/cfa/styleguide/pages/index.html.erb
app/views/layouts/main.html.erb
lib/cfa/styleguide/engine.rb
lib/cfa/styleguide/version.rb
spec/feature/pages_spec.rb

They previously defined all of their own HTML. Now we have them all
inserted into the base layout, similar to the main page.
This commit also precompiles the cfa styleguide assets, and only
includes those stylesheets and javascript + Prism on the styleguide
pages.

Fix styling on non-main styleguide pages

---

app/assets/stylesheets/atoms/_variables.scss
app/views/examples/atoms/_colors.html.erb

A fix for the issue described here: https://github.com/codeforamerica/cfa-styleguide-gem/issues/18
If I slightly darken our base teal color, the accessibility checks are happy with the contrast on all sizes of buttons (including `.button--small`). Here's what that same page on the styleguide looks like:
(as comparison, here's the original that's not contrasting enough now):
There are other ways we can address the contrast (bigger font, mainly), but this felt least intrusive. What do you think, @norrishung? Look acceptable?

Darken base teal color to improve contrast

---

README.md
bin/rails
spec/test_app/config/environments/development.rb

- Adds a rails executable to allow running bin/rails s directly from this gem for easier development.
- Expands the readme to explain how to use Bundler's local config overrides when developing against another Rails project. This is a good explanation: https://rossta.net/blog/how-to-specify-local-ruby-gems-in-your-gemfile.html
Connects to #34 (everything except the minimum Ruby version)

Add development Rails server and update development instructions

---

app/models/cfa/styleguide/form_example.rb

Replaces Rails' auto-generated messages with one that shows something more like we want our application to show (capitalization, punctuation).
Closes https://github.com/codeforamerica/cfa-styleguide-gem/issues/62
Here's an example:

Update styleguide error message

---

Gemfile.lock
README.md
app/assets/stylesheets/atoms/_variables.scss
lib/cfa/styleguide/version.rb

Uses `!default` so that variables will not ovewrite an existing variable
Based on @bensheldon's recommendation
https://github.com/codeforamerica/cfa-styleguide-gem/issues/17#issuecomment-458303518
This allows rails apps  to define their own variables _before_ importing the styleguide scss, and those values will be used throughout the guide.
For example, in my app:
```scss
// in app/assets/stylesheets/_my_variables.scss
$color-background:    #666;
```
```scss
// in app/assets/stylesheets/application.scss
@import 'my_variables';
@import 'cfa_styleguide_main';
```
`$color-background` would now be defined as `#666`.
I tested this locally on a prototype app.

Allow overriding variables

---

app/views/cfa/styleguide/pages/_section.html.erb

Closes #53.
This adds individual anchorlinks to each component example. It builds on the `_section.erb` partial, which has not been completely used for all examples; so there isn't a link for every example. If this is the path to take, I can (separately) convert all the examples to use the partial.

Add anchorlink to individual examples

---

app/views/cfa/styleguide/pages/_section.html.erb
app/views/cfa/styleguide/pages/index.html.erb

I'm not in love with the icon differentiating the anchor link from the link to the isolated example (I just picked something ascii), but it was expedient. Linking to the partial is very useful for inspecting with Axe/Wave/Voiceover and raises the visibility for future features like visual diff tests.

Refactor all styleguide examples to use partial; add link to isolated example

---

app/assets/stylesheets/molecules/_incrementer.scss

Before
After
Closes https://github.com/codeforamerica/cfa-styleguide-gem/issues/94

Remove stepper arrows for number input on Firefox

---

app/assets/stylesheets/molecules/_progress-step-bar.scss
app/views/components/molecules/_progress_step_bar.html.erb
app/views/examples/molecules/_progress_step_bar.html.erb

Finishes https://github.com/codeforamerica/cfa-styleguide-gem/issues/105
Usages:
```
<%= render partial: 'components/molecules/progress_step_bar', locals: { current_step: 3, step_count: 5, step_description: 'Basic Info' } %>
<%= render partial: 'components/molecules/progress_step_bar', locals: { current_step: 3, step_count: 5, step_name: 'Section', step_description: 'Basic Info' } %>
```

Add support for optional progress step bar labels

---

app/views/components/molecules/_progress_step_bar.html.erb
app/views/examples/molecules/_progress_step_bar.html.erb

@hartsick unsure if we are trying to preface the sections, but it runs into an awkward problem at the end of the steps where the current step is greater than the total number of steps

Fix bug on step progress bar: increment current_step on a 0 index system

---

app/views/components/molecules/_progress_step_bar.html.erb
app/views/examples/molecules/_progress_step_bar.html.erb

because the current way is unconducive for Chinese translations

Simplified step-bar-description

---

app/assets/javascripts/cfa_styleguide_main.js
app/views/examples/molecules/_follow_up_question.html.erb

It looks like the follow-up question component _was_ intended to work
with checkboxes (since it clears the checked state proactively), but in
practice it didn't: When unchecking the checkbox, the call to $.show()
would trigger, resulting in the follow-up never disappearing.
By copying the conditional logic used during initialization here, we can
make it work for a single checkbox.
I've added an example to the styleguide page to assist future
implementers.

Fix follow-up to work for single checkbox

---

app/assets/javascripts/cfa_styleguide_main.js

We want to do a progressive enhancement follow up question in GCF, where
the follow up is shown by default and hidden with JS. It looks like the
inverse of the necessary logic already existed -- to expand follow-up
questions that were checked -- so this commit updates the logic to also
hide follow-up questions that are unchecked.
(Note: Consumers of the component will have to set "display:
block" on the component themselves to get the progressive enhancement
behavior.)

Hide unchecked follow up questions on page load

---

app/assets/images/icon_accordion_close.svg
app/assets/images/icon_accordion_open.svg
app/assets/javascripts/cfa_styleguide_main.js
app/assets/stylesheets/cfa_styleguide_main.scss
app/assets/stylesheets/molecules/_accordion.scss
app/views/cfa/styleguide/pages/index.html.erb
app/views/examples/molecules/_accordion.html.erb

This PR adds an accordion pattern to our styleguide:
- Includes accordion css
- Includes accordion javascript
- Includes an accordion html example
- Adds the accordion example and description to the styleguide index page
Testing:
- Accordion has been tested for responsive design (Mobile Safari and Desktop Safari)
- Accordion has been tested for cross-browser compatibility (Chrome, Safari, Firefox)
- Accordion has been tested in Desktop Safari with Javascript disabled.
- Accordion has been tested with VoiceOver on iOS on an iPhone X
Notes on graceful degradation, accessibility, and css:
1. This accordion is open (and therefore visible) by default if there is no javascript enabled. If javascript is enabled, it closes the accordion on document ready and adds an "click" event listening to …

Adding an accordion pattern

---

.gitignore
app/assets/stylesheets/atoms/_typography.scss
app/views/examples/atoms/_typography.html.erb

This pull request adds `list--checkmark` and `list--crossmark` patterns to the honeycrisp design system. They are necessary for the immigration guide page on GCF but we think they will be useful across other projects as well.
This has been checked for cross-browser compatiability (Safari, Firefox, Chrome, and Mobile Safari). It has also been checked for responsive design.

Add crossmark and checkmark list patterns to design system

---

app/assets/stylesheets/templates/_styleguide.scss
app/helpers/cfa/styleguide/pages_helper.rb
app/views/cfa/styleguide/pages/_section.html.erb
app/views/cfa/styleguide/pages/emojis.html.erb
app/views/cfa/styleguide/pages/index.html.erb
app/views/examples/atoms/_labels.html.erb
app/views/layouts/main.html.erb

Also:
- add new explanations to some elements (from Rachel)
- fix the labels example template

Documentation page: display explanation between example and code

---

MIGRATING.md
README.md

This takes a stab at making a migration guide for use with https://github.com/codeforamerica/cfa-styleguide-gem/pull/123, with the intention of making it easier for people outside CFA to upgrade between versions. 
This PR should be merged after 123 is merged to master, before or as part of the release of 0.8.0.

[do not merge] Add migration guide

---

CHANGELOG.md
MIGRATING.md
README.md
Rakefile
app.json
app/views/cfa/styleguide/pages/index.html.erb
app/views/layouts/main.html.erb
cfa-styleguide.gemspec

* Update Github link to new repo name
* Update Heroku URL -> honeycrisp.herokuapp.com
Closes https://github.com/codeforamerica/honeycrisp-gem/issues/122

Update branding to Honeycrisp

---

app/views/examples/organisms/_pagination.html.erb

Closes #149
Co-authored-by: Ben Sheldon <ben@codeforamerica.org>

Change from <button> to <a> elements for pagination

---

app/assets/stylesheets/atoms/_form-elements.scss
app/assets/stylesheets/atoms/_utilities.scss

The previous solution had two issues: the focus was rectangular despite the rounded rect button style, and the upload button lost its spacing, causing GCF's documents upload page to lay out incorrectly. This is a bit of a sketchy fix, since it relies on the existence of an element with class 'button' (which is actually an unfocused <label> in GCF) as a sibling of the actually-focused input element (which is invisible in GCF's case). I still need to test this in other instances of GCF's usage if there are any, but wanted to push it up to let others tell me if it's totally infeasible in the meantime.

Adjusts how upload buttons are highlighted on focus.

---

app/assets/stylesheets/molecules/_form-molecules.scss
app/views/examples/molecules/_text_input_group.html.erb

- added example of postfix and prefix combinations
- fixes issue #144
Co-authored-by: Symonne Singleton <symonne@codeforamerica.org>

Fixed spacing on text input groups

---

app/helpers/cfa/styleguide/pages_helper.rb

Rails 6 no longer returns a path when inspecting an Action View template, which causes the style guide pages to break in Rails 6 apps. This change addresses that and restores access to the Honeycrisp pages.

Use `identifier` to return a path for desired template.

---

app/views/examples/atoms/_form_elements.html.erb
spec/system/accessibility_spec.rb
spec/system/formatted_input_spec.rb

This adds labels to all the form input examples so that we can pass accessibility checks and set a better example.

Add labels to form input examples

---

app/assets/stylesheets/_honeycrisp-compact.scss
app/views/examples/honeycrisp_compact/_form_elements.html.erb

Additional changes not requested in the story:
- This reduces the bottom margin on `.form-group` elements from 60px to 35px in Honeycrisp Compact
- Using normal font weight inside the inputs instead of bold (700)
Closes #202

Add compact text input styling

---

app/assets/javascripts/cfa_styleguide_main.js

This looks like it was removed with this change. Not sure if it's intended to be deprecated or not
https://github.com/codeforamerica/honeycrisp-gem/pull/3
Component is currently not working in the styleguide

Fix - Readd incrementer.init()

---

app/assets/stylesheets/atoms/_buttons.scss

This allows styling a disabled button purely by adding the `disabled` property, instead of having to both add the `.button--disabled` _and_ the `disabled` property.

Style disabled buttons directly via disabled property

---

Gemfile.lock
app/assets/stylesheets/cfa_styleguide_main.scss
cfa-styleguide.gemspec
lib/tasks/distribution.rb
vendor/assets/stylesheets/neat/_neat-helpers.scss
vendor/assets/stylesheets/neat/_neat.scss
vendor/assets/stylesheets/neat/functions/_new-breakpoint.scss
vendor/assets/stylesheets/neat/functions/_private.scss
vendor/assets/stylesheets/neat/grid/_box-sizing.scss
vendor/assets/stylesheets/neat/grid/_direction-context.scss
vendor/assets/stylesheets/neat/grid/_display-context.scss
vendor/assets/stylesheets/neat/grid/_fill-parent.scss
vendor/assets/stylesheets/neat/grid/_media.scss
vendor/assets/stylesheets/neat/grid/_omega.scss
vendor/assets/stylesheets/neat/grid/_outer-container.scss
vendor/assets/stylesheets/neat/grid/_pad.scss
vendor/assets/stylesheets/neat/grid/_private.scss
vendor/assets/stylesheets/neat/grid/_row.scss
vendor/assets/stylesheets/neat/grid/_shift.scss
vendor/assets/stylesheets/neat/grid/_span-columns.scss
vendor/assets/stylesheets/neat/grid/_to-deprecate.scss
vendor/assets/stylesheets/neat/grid/_visual-grid.scss
vendor/assets/stylesheets/neat/mixins/_clearfix.scss
vendor/assets/stylesheets/neat/settings/_disable-warnings.scss
vendor/assets/stylesheets/neat/settings/_grid.scss
vendor/assets/stylesheets/neat/settings/_visual-grid.scss

to use the latest Rails, we need to be able to use thor 1.x,
and `neat` locked it to an old version.
Fixes #232

vendorize `neat` 1.8.0 to relax dependency on old thor

---

app/assets/stylesheets/_honeycrisp-compact.scss
app/assets/stylesheets/atoms/_variables.scss
app/views/cfa/styleguide/pages/honeycrisp_compact.html.erb
app/views/examples/honeycrisp_compact/_buttons.html.erb
app/views/examples/honeycrisp_compact/_data_table.html.erb
app/views/examples/honeycrisp_compact/_form_elements.html.erb
app/views/examples/honeycrisp_compact/_typography.erb

Updates Honeycrisp Compact for recent style changes, represented here: https://www.figma.com/file/cW21hUVdIn5IcnxpjF5Cq1/Honeycrisp-working-file?node-id=295%3A195
Notable updates: 
- Adds some new button types (small and large)
- Makes spacing smaller
- Adds typography elements, h1, h2, h3 
- Fixes lost focus outline https://github.com/codeforamerica/honeycrisp-gem/issues/230
- Changes link colors for error or warning text in table 
Design consideration: 
The majority of the spacing and size variables are hard-coded here for font and line spacing. This is because Honeycrisp itself is very opinionated about how much line spacing goes with font size. Adding variables for Honeycrisp Compact to the variables file seemed like overkill since the sizes are not shared. 
Co-authored-by: Whitney …

Updating honeycrisp compact styles 

---

app/assets/javascripts/cfa_styleguide_main.js

Thanks for a great bug report @lkogler @wschaefer -- when you said incrementor was incrementing by two, it seemed likely we were calling Honeycrisp.init() 2x, which was adding double listeners! 
Honeycrisp.init() is also being called at the end of  honeycrisp.js itself, so we don't need the call to Honeycrisp.init() in the manifest.

Remove double init of honeycrisp javascript.

---

app/assets/stylesheets/atoms/_variables.scss
app/assets/stylesheets/molecules/_tabs.scss

closes #152 
It was originally proposed to set the background color of selected tabs to white in order to differentiate the selected tab from the unselected tabs in a tab bar. 
After some discussion between @bengolder and @racheledelman , it was noted that the tab bar looks different in the styleguide than it does on most projects. The selected tab used `$background-color`, which was white for the styleguide, while the tab bar itself was set to `$color-grey-light`, so the selected tab stood out by accident in the styleguide and blended in in other places like GCF. 
This PR sets the tab bar to use the background color darkened by 5%. A selected tab will show the normal background color. Below you can see the difference more clearly: 
Before on GCF 
After on GCF

Darkens unselected tabs by 5% in tab bar

---

app/assets/javascripts/honeycrisp.js
app/assets/stylesheets/atoms/_form-elements.scss
app/views/cfa/styleguide/pages/index.html.erb
app/views/examples/form_builder/_cfa_radio_set.html.erb
app/views/examples/molecules/_follow_up_question.html.erb
spec/system/accessibility_spec.rb
spec/system/follow_up_question_spec.rb

Co-authored-by: Laura Kogler <lkogler@codeforamerica.org>

Fix checkbox set with followup so that selecting additional checkboxes leaves followup open

---

app/assets/stylesheets/_honeycrisp-compact.scss
app/views/examples/honeycrisp_compact/_data_table.html.erb

We need this for the GCF CBO dashboard.
This also updates <th> link styles so that only the links in <td>'s are
colored green.
Co-authored-by: Travis Grathwell <tgrathwell@codeforamerica.org>

Add .header--sortable to honeycrisp_compact data-table

---

app/assets/stylesheets/atoms/_grid.scss

Fixes #235. 
We were setting a value for max-width twice on .grid. Since the outer container mixin already supports passing in a custom max width, we can pass in the value we want instead of overriding it.

Consolidate max width logic

---

app/helpers/cfa/styleguide/cfa_v2_form_builder.rb
spec/helpers/cfa_v2_form_builder_spec.rb

Prevent autocompletion by browser, autocorrect, autocapitalization, and
spellcheck. Belief is that they are not desirable for our main use cases
(eg shared computers or data entry for multiple people, phones &
names & addresses).
Can be overriden by passing HTML options to form field.
This matches behavior for our previous form builder.
MDN docs:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-autocorrect (non-standard)
And:
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
Closes …

Set default attributes on relevant inputs

---

README.md

When trying to use the honeycrisp gem, we ran `bundle install` and received the error: 
```
fatal: Needed a single revision
Revision master does not exist in the repository https://github.com/codeforamerica/honeycrisp-gem. Maybe you misspelled it?
```
In order to get `bundle install` to work, we needed to specify `main` as the branch name in Gemfile. See: https://github.com/rubygems/rubygems/issues/4009

update readme to specify 'main' as the branch name

---

app/assets/javascripts/honeycrisp.js
app/assets/stylesheets/honeycrisp/molecules/_reveal.scss
spec/system/reveal_spec.rb

- Changes reveal class `is-hidden` to `is-hiding-content`
- Adds a test suite for the reveal component
- Closes #275

Fix reveal and add tests

---

Gemfile.lock
cfa-styleguide.gemspec
package.json
spec/support/percy_snapshot.rb
yarn.lock

Relates to #296
[Upgrades `@percy/agent` to `@percy/cli`](https://docs.percy.io/docs/migrating-to-percy-cli) (and [updates `percy-capybara`](https://docs.percy.io/docs/capybara#upgrading)) as to [remove the dependency of `axios`](https://github.com/codeforamerica/honeycrisp-gem/security/dependabot/yarn.lock/axios/open)
Checking to see if the Percy build step in this PR passes with the migration change.
- Tests did [pass](https://app.circleci.com/pipelines/github/codeforamerica/honeycrisp-gem/659/workflows/7556d253-0733-40f3-8deb-c8a952ec9db0/jobs/1595).
- [Percy generated snapshots, with no diffs](https://percy.io/Code-for-America/honeycrisp-gem/builds/12691181/unchanged/716776009?browser=chrome&viewLayout=overlay&viewMode=new&width=1280) (which is correct)
After merging this PR, these …

Update @percy/agent to @percy/cli

---

app/assets/stylesheets/honeycrisp/molecules/_form-molecules.scss

Fix #300 by using `opacity` instead of `display: none` to hide custom inputs.

Allow feedback survey radio to accept focus

---

.rubocop.yml
app/helpers/cfa/styleguide/cfa_form_builder.rb
app/models/cfa/styleguide/form_example.rb

We jumped the gun on removing unused `&block` variable names -- that syntax isn't supported until Ruby 3.1.
Until then, let's keep these anonymous block arguments.

Fix syntax error on Ruby 3.0

---

.circleci/config.yml
app/assets/javascripts/honeycrisp.js
app/assets/stylesheets/honeycrisp/molecules/_reveal.scss
app/views/components/molecules/_reveal.html.erb

Allows Safari screenreaders to announce expanded/collapsed state of the reveal when clicked/pressed on to open/close
https://www.pivotaltracker.com/story/show/186891325

Make reveal more accessible

---

MIGRATING.md
app/assets/stylesheets/honeycrisp/molecules/_reveal.scss

Merged recent updated version of honeycrisp (0.12.0) to GCF codebase and saw that percy diff showed change in alignment of the button text when viewed in a small screen.

Set text align start on reveal button

---

app/assets/javascripts/honeycrisp.js

Fix for when there are mutiple checkbox sets on one page - the "none of the above" toggle will be applied only to its own set (instead of every checkbox set on the page)
⚠️ Breaking change for folks using `id="none__checkbox"` without the "input name" appended ex `id="none__checkbox-programSelection"`

Fix - "None of the above" in checkbox set (Breaking)

---

Gemfile.lock

I ran the recommended command and it changed the gemlock file for me, so I created a PR to address it.
```
arin✨ honeycrisp-gem [main] bundle exec rake release\[0.13.1\]
== Bumping version number ==
Uncommitted changes found. Please commit or stash. Aborting.
== Command ["gem bump --no-commit --version 0.13.1"] failed ==
arin✨ honeycrisp-gem [main] git st
On branch main
Your branch is up to date with 'origin/main'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   Gemfile.lock
no changes added to commit (use "git add" and/or "git commit -a")
arin✨ honeycrisp-gem [main] git add -p
diff --git a/Gemfile.lock b/Gemfile.lock
index 3d6e001..4586799 100644
--- a/Gemfile.lock …
```

Update rails in the format recommended

---

app/assets/javascripts/honeycrisp.js

Reverts codeforamerica/honeycrisp-gem#320
-- 
This broke the functionality for Rails projects, which use formbuilder. We cannot easily manipulate the id of the html elements as in we can in our java projects. In order to unblock further development for Rails projects, we made a decision to revert this. We should figure out a way to fix this for java projects in the future.

Revert "Fix - "None of the above" in checkbox set (Breaking)"

---

Rakefile

Moved the release steps into a separate method `execute_release_steps` to improve code modularity.
Enforced that system! commands abort on failure, and added handling in `add_jquery_to_path` for cases where the jQuery path is not found.

`Rakefile` update and improvements.

---

lib/sprockets_extension/uglifier_source_maps_compressor.rb

Move the `uglifier` initialization out of the method to avoid re-initializing it every time the method is called.
Used `File.join` for constructing file paths to ensure compatibility across different operating systems.
Included the necessary `json` and `fileutils` libraries explicitly.

Move the `uglifier` initialization out of the method to avoid re-initializing it every time the method is called.

---

app/assets/stylesheets/honeycrisp/atoms/_form-elements.scss

[GCF-465](https://codeforamerica.atlassian.net/browse/GCF-465?atlOrigin=eyJpIjoiYTlhOGNhOWEwOGFhNDhlYmIxYmQ0NWEwZjY0NDU1YzEiLCJwIjoiaiJ9)
[GCF-465]: https://codeforamerica.atlassian.net/browse/GCF-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Used to be `-apple-system-blue`:
No longer blue

Set `.select__element` color to inherit instead of using safari default for `select` elements
